### PR TITLE
Add configurable test web server

### PR DESCRIPTION
**Pull request by DonnchaC**
This commit adds a test web server which will show different performance characteristics based on a configuration of a set of edge servers.

This web server uses the last octet of the request IP address as the edge ID. This edge ID is then used to identify the target edge configuration from the config file.

Sample output:
```
2016-07-20 12:43:28,393 [INFO]: Loaded 10 edges from config test_data/test_edge_config.yaml.
2016-07-20 12:43:53,558 [INFO]: Request for unknown edge 106
2016-07-20 12:43:55,854 [INFO]: Serving edge 105 after a 5 second delay
2016-07-20 12:44:04,282 [INFO]: Closing connection for offline edge 104.
2016-07-20 12:44:04,391 [INFO]: Closing connection for offline edge 104.
2016-07-20 12:44:09,404 [INFO]: Closing connection for offline edge 104.
2016-07-20 12:44:15,873 [INFO]: Serving edge 3 after a 1 second delay
2016-07-20 12:44:42,122 [INFO]: Serving edge 101 after a 15 second delay
```

### CODE REVIEW

**Comment by DonnchaC** [comment]
I'm running some tests to understand how `edge_manage` is performing requests. With the patch in #34 it now looks like 10 requests are being made simultaneously. However there is a bug where one canary is being retried 20 times instead of each canary being retried once when it fails. I'm going to look for a solution to this now.

The request logs from my test server: https://gist.github.com/DonnchaC/7e8e6439ae6c02780e64dd9dc37467b9

**Comment by DonnchaC** [comment]
When writing these tests I noticed that the edge state files are not updated to indicate that an edge has failed or timed out. When a connection to an edge hits the timeout limit it still set with `"health": "pass"` and `"mode": "available"`.

I'm not certain if this is intended behavior, but I think the failing state should be noted in the `.edgestate` file rather than just checking for a timeout in `DecisionMaker.check_threshold()`. Is this a bug?

**Comment by DonnchaC** [comment]
@tomryanx  @kheops2713 It would be good to get your feedback on these changes, this this fix any problems that you have been experiencing?

With these integration tests we are better positioned to fix issues that arise with edge testing. Next I'll write a test and start working on #28.

**Comment by tomryanx** [comment]
I think you're on the right track @DonnchaC 

Marking an edge as failed after a timeout sounds logical.

What you're seeing to do with canaries being retried and poor use of parallelisation is a great fit with my anecdotal theory that: when all canaries are timing out, it has catastrophic consequences for edgemanage performance.

While I'm wary of assuming that my suspicion was correct based on this, it does _look_ like what you've already identified (combined with the canary_killer in #28) could solve things nicely.

**Comment by DonnchaC** [comment]
I've merged these tests now. I'll work on #28 in a separate branch.

**Pull request merged**
